exports.CONST_FRIDAY_EVENING = 1.40,
exports.CONST_SATURDAY_EVENING = 1.30,
exports.CONST_SUNDAY_EVENING = 0.90,
exports.CONST_FRIDAY_AFTERNOON = 1.00,
exports.CONST_SATURDAY_AFTERNOON = 0.90,
exports.CONST_SUNDAY_AFTERNOON = 0.80;
exports.DEFAULT = 1.00;